//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.MarkomApplication.ModelData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_MarkomEntities : DbContext
    {
        public Db_MarkomEntities()
            : base("name=Db_MarkomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_souvenir> m_souvenir { get; set; }
        public virtual DbSet<m_unit> m_unit { get; set; }
        public virtual DbSet<m_product> m_product { get; set; }
        public virtual DbSet<m_employee> m_employee { get; set; }
        public virtual DbSet<t_souvenir_item> t_souvenir_item { get; set; }
        public virtual DbSet<t_souvenir> t_souvenir { get; set; }
    }
}
