//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.MarkomApplication.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_souvenir
    {
        public long id { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public Nullable<long> t_event_id { get; set; }
        public long request_by { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<System.DateTime> request_due_date { get; set; }
        public Nullable<long> approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<long> received_by { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<long> settlement_by { get; set; }
        public Nullable<System.DateTime> settlement_date { get; set; }
        public Nullable<long> settlement_approved_by { get; set; }
        public Nullable<System.DateTime> settlement_approved_date { get; set; }
        public Nullable<int> status { get; set; }
        public string note { get; set; }
        public string reject_reason { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
